pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        maven {
            name = "RedlanceMinecraft"
            url = "https://repo.redlance.org/public"
        }

        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}